### ISSUE TITLE
Make the student/index.php more user friendly

### ISSUE THREAD

**Issue by devdil** [devdil/www.gnooble.org#4]
![issue](https://cloud.githubusercontent.com/assets/5098875/5676394/36494972-97fb-11e4-85a4-6b9f8a1de70a.jpg)

Things to add
1) a profile picture block for the image section
2)style the fonts 
3)make it a bit attractive

**Comment by maxxon15** [comment]
@devdil You forgot to assign this to me. I didn't get any notifs! :/

**Comment by maxxon15** [comment]
@devdil Okay. Few questions:
When are the users updating the images in the onboarding process? It wasn't there initially.

Fonts are okay. Its important not to choose fancy fonts for a site that is oriented towards developers rather than consumers. Besides, the font is Open Sans, which is one of the best humanist fonts out there that you can get for free.

**Comment by devdil** [comment]
I will update the database and add a room for images too...
Just make it a bit attractive...

**Comment by maxxon15** [comment]
@devdil Okay. But I'd advise not to include images as a necessary requirement while signing up. We should do it like facebook does.. takes only the essential details, and then after signing up, the user should have freedom whether they want to put up an image or not. Smoother onboarding.

I'll try something with the layout. I think we should root for something that is fast, usable and simple rather than attractive visual design.
Students won't come to the site to look at the fancy UI. THe objective - I believe is to get out of their way and let them compile their code online. Isn't it?

**Comment by devdil** [comment]
Exactly you got it right....

**Comment by maxxon15** [comment]
@devdil Yeah.

And while we're on the subject, I think we should remove the contact number from the registration process too. This removes any additional friction and let the user signup as fast as they can without thinking twice.

**Comment by devdil** [comment]
notify me once you push your updates
